name: Repository Dispatch
on:
  repository_dispatch:
    types: [trigger-tests]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.preview_url }}
      - run: echo ${{ github.event.client_payload.tags }}

      - name: Checkout
        uses: actions/checkout@v2
  
      # https://github.com/cypress-io/github-action
      # Installs and caches dependencies, runs all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
        with:
          config: baseUrl=${{ github.event.client_payload.preview_url }}
          env: grepTags=${{ github.event.client_payload.tags }}


      - name: Set commit status to calling repo
        if: ${{ github.event.client_payload.sha }}
        uses: Sibz/github-status-action@v1
        with:
          # create personal GitHub token to be able to
          # set status in other repositories
          # https://github.com/settings/tokens/new
          authToken: ${{ secrets.REPO_ACCESS_TOKEN }}
          context: 'E2E tests'
          description: 'Cypress ran the tests'
          # state can be success, error, failure, or pending
          # let's grab it from the Cypress step outcomes
          # https://github.com/cypress-io/github-action#outputs
          state: ${{ steps.cypress.outcome }}
          owner: 'saisiddulugari'
          repository: 'cypress-e2e-test-app'
          sha: ${{ github.event.client_payload.sha }}
